services:
  web:
    build: .
    image: speeddating
    container_name: speeddating_website
    ports:
      - "${SD_EXTERNAL_PORT}:3000"
    env_file:
      - .env
    networks:
      - network



  mongodb:
    image: mongo:latest
    container_name: speeddating_mongodb
    ports:
      - "${SD_MONGO_PORT}:27017"
    volumes:
      - speeddating-data:/data/db
    env_file:
      - .env
    networks:
      - network
    
    
volumes:
  speeddating-data:
    driver: local

networks:
  network:
    driver: bridge