services:
  web:
    build: .
    image: speeddating
    container_name: speeddating_website
    ports:
      - "${EXTERNAL_PORT}:3000"
    env_file:
      - .env
    networks:
      - network

  mongodb:
    image: mongo:latest
    container_name: speeddating_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - speeddating-data:/data/db

    env_file:
      - .env
    networks:
      - network
    command: mongod
    
    
volumes:
  speeddating-data:
    driver: local

networks:
  network:
    driver: bridge